name: Setup Flutter

description: Setup Flutter environment on GitHub Actions runner.

inputs:
  GITHUB_ACCESS_TOKEN:
    description: 'GitHub Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    # Flutter SDKをインストール
    - name: Install Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b stable ${{ runner.tool_cache }}/flutter
        echo "${{ runner.tool_cache }}/flutter/bin" >> $GITHUB_PATH
        echo "${{ runner.tool_cache }}/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
        echo "${{ runner.tool_cache }}/flutter/.pub-cache/bin" >> $GITHUB_PATH
        flutter precache
        flutter doctor
      shell: bash

    # Flutterの依存関係を取得
    - name: Get Flutter dependencies
      run: flutter pub get
      shell: bash

    # flutter_envスクリプトに実行権限を付与
    - name: Grant execute permission to flutter_env
      run: chmod +x bin/flutter_env
      shell: bash

    # 環境変数ファイル（env.dart）を作成
    - name: Create env.dart
      run: bin/flutter_env -g ${{ inputs.GITHUB_ACCESS_TOKEN }}
      shell: bash