name: my_gourmet
description: A new Flutter project.
# 意図せず`flutter pub publish` によってpub.devに配信されることを防止する
publish_to: 'none'

version: 1.0.1+12

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  appinio_swiper: ^2.1.1
  cached_network_image: ^3.4.0
  camera: ^0.11.0+2
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  collection: ^1.17.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^10.1.0
  drift: ^2.20.3
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_remote_config: ^5.0.4
  firebase_storage: ^12.1.3
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geolocator: ^13.0.1
  go_router: ^14.2.3
  google_sign_in: ^6.1.4
  hooks_riverpod: any
  http: ^1.2.1
  image: ^4.2.0
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  logger: null
  package_info: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_manager: ^3.0.0
  roggle: ^0.4.2+1
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^6.1.2
  smooth_page_indicator: ^1.1.0
  sqlite3_flutter_libs: ^0.5.22
  url_launcher: ^6.2.4


# ビルドで失敗したため、一旦除外。セキュリティリスクのため後で対応。
# recaptcha_enterprise_flutter: ^18.4.0

dev_dependencies:
  build_runner: ^2.4.10
  change_app_package_name:
  custom_lint: ^0.6.4
  drift_dev: ^2.20.3
  flutter_native_splash: ^2.3.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pedantic_mono: any
  riverpod_lint: ^2.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: '#EF913A'
  image: 'assets/images/splash/splash.png'
  color_dark: '#EF913A'
  image_dark: 'assets/images/splash/splash.png'
  android_12:
    icon_background_color: '#EF913A'
    image: 'assets/images/splash/splash_android12.png'
    icon_background_color_dark: '#EF913A'
    image_dark: 'assets/images/splash/splash_android12.png'

flutter:
  assets:
    - assets/images/
    - assets/images/sign_in/
    - .env
  fonts:
    - family: ZenkakuGothicNew
      fonts:
        - asset: assets/fonts/ZenKakuGothicNew-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenKakuGothicNew-Regular.ttf
        - asset: assets/fonts/ZenKakuGothicNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenKakuGothicNew-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenKakuGothicNew-Black.ttf
          weight: 900
  uses-material-design: true
