name: my_gourmet
description: A new Flutter project.
# 意図せず`flutter pub publish` によってpub.devに配信されることを防止する
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_storage:
  firebase_auth: ^4.7.1
  cloud_functions:
  cloud_firestore:
  google_sign_in: ^6.1.4
  http: ^0.13.3
  logger:
  flutter_riverpod: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.4
  riverpod_lint: ^2.1.1
flutter:
  assets:
    - assets/images/
  uses-material-design: true