name: my_gourmet
description: A new Flutter project.
# 意図せず`flutter pub publish` によってpub.devに配信されることを防止する
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: any
  cloud_functions: any
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  firebase_auth: any
  firebase_core: any
  firebase_remote_config: any
  firebase_storage: any
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.0
  google_sign_in: ^6.1.4
  http: ^0.13.3
  logger: null
  package_info: ^2.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  flutter_native_splash: ^2.3.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pedantic_mono: any
  riverpod_lint: ^2.1.1

flutter_native_splash:
  color: '#EF913A'
  image: 'assets/images/splash/splash.png'
  color_dark: '#EF913A'
  image_dark: 'assets/images/splash/splash.png'
  android_12:
    icon_background_color: '#EF913A'
    image: 'assets/images/splash/splash_android12.png'
    icon_background_color_dark: '#EF913A'
    image_dark: 'assets/images/splash/splash_android12.png'

flutter:
  assets:
    - assets/images/
    - .env
  fonts:
    - family: ZenkakuGothicNew
      fonts:
        - asset: assets/fonts/ZenKakuGothicNew-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenKakuGothicNew-Regular.ttf
        - asset: assets/fonts/ZenKakuGothicNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenKakuGothicNew-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenKakuGothicNew-Black.ttf
          weight: 900
  uses-material-design: true
