// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1bSY10I1tRZTeJj4s_RFhp5GEOvRK3Y',
    appId: '1:588802119789:android:813b3a0dc8542f79b4c764',
    messagingSenderId: '588802119789',
    projectId: 'my-gourmet-160fb',
    storageBucket: 'my-gourmet-160fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHiEFqj1KOpzYLhCKGOWkF21pIZ6wOdhc',
    appId: '1:588802119789:ios:421aa538ce40863db4c764',
    messagingSenderId: '588802119789',
    projectId: 'my-gourmet-160fb',
    storageBucket: 'my-gourmet-160fb.appspot.com',
    androidClientId: '588802119789-6hda24f2u719ais2ul1o2odjauq9n29m.apps.googleusercontent.com',
    iosClientId: '588802119789-oh11a15chog7l1dkq0q4ju5gh4gofcut.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGourmet',
  );
}
